name: chestxsim_testing
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - astra-toolbox
  - numpy=1.26.4
  - matplotlib=3.10.3
  - pydicom=3.0.1
  - scikit-image=0.21.0
  - fastai=2.7.13
  - fastcore=1.5.55
  # CUDA-enabled PyTorch 2.1
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=12.1        
  - pip:
      - cupy-cuda12x==13.3.0
      - -e .                 